### ISSUE TITLE
Lack of usefull content to prepare the DA-100

### ISSUE THREAD

**Issue by Didierma92** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#1]
# Module: 00
#### Step: 00

Lack of usefull content to prepare the DA-100. WHen will it be released ?

Repro steps:

1.Cannot find any .pbit or pbix
1.Cannot find any source
1.

**Comment by FrankGT001** [comment]
where can you download the files for labs and solved labs?

**Comment by FrankGT001** [comment]
> # Module: 00
> ## Lab/Demo: 1
> ### Task: 00
> #### Step: 00
> Lack of usefull content to prepare the DA-100. WHen will it be released ?
> 
> Repro steps:
> 
> 1.Cannot find any .pbit or pbix
> 1.Cannot find any source
> 1.

could you solve it?

**Comment by HappymediaDz** [comment]
Not just that.
The **\DA100\Setup\** folder is missing, it should include the "**_MySettings.txt_**" file and the "**_UpdateDatabase-1-UpdateAccount.ps1_**"
Will all that content, including the "**_AdventureWorksDW2020_**" database, be provided with the second part of the download on the MCT Download Center ?

**Comment by ilikesql** [comment]
The virtual machine hosted by each of the our authorized lab hosters have all files on the D:\ drive.

**Comment by HappymediaDz** [comment]
Will the course provide local VMs or the course will be run only from authorized lab hosters

**Comment by douwevandenberg** [comment]
I've just tried it at XtremeLabs and that one isn't ready.

**Comment by ilikesql** [comment]
Following up on this:
- all VMs needed for these labs are available through authorized lab hosters.
- We also published the labs in a hosted platform through /Learn
- as per future direction, if the desired state would be to provide a separate download of the course files and provide a setup guide to spin up your own environment, please let me know

**Comment by GitMonkey3** [comment]
I would really appreciate if the setup guide and lab files were available for download.

**Comment by shannonlindsay** [comment]
@GitMonkey3 - all files are available for download here: https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/tree/master/Allfiles/DA-100-Allfiles
