### ISSUE TITLE
Lab 1 - References to other labs

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#10]
There are 2 references to labs that do not exist in current lab portfolio, probably because their numbers have changed:

> You will publish content to the workspace in Lab 03D.

> These facts will become relevant when implementing row-level security in Lab 03B.

Also, the remaining reference does not point to the lab it seems to intend to reference:

> You will commence the development of a data model in Lab 02A.

Data modeling lab is currently Lab 4A and 5A for advanced data modeling.

_Edit: Other labs would benefit from a similar update to references._

**Comment by shannonlindsay** [comment]
Hi @VitalyMCT - references to other labs have been removed in the lab instructions.
