### ISSUE TITLE
Run fails due to error

### ISSUE THREAD

**Issue by JoshuaRoweTTS** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#103]
# Module: 11
### Step 34, 21

o	Run fails due to the below error

![image](https://user-images.githubusercontent.com/80295628/112454446-698e0480-8da4-11eb-846b-5766e933a07f.png)

**Comment by shannonlindsay** [comment]
@JoshuaRoweTTS - I am not able to recreate this issue. @weslbo - have you seen this issue in the paginated report lab?

**Comment by weslbo** [comment]
Usually this error happens when the Expression is not correct (or even only contains =)

![image](https://user-images.githubusercontent.com/53346841/116655057-ac865d80-a98a-11eb-9276-4072ede7b918.png)

**Comment by shannonlindsay** [comment]
Thanks Wesley. I am closing this issue as a false positive.
