### ISSUE TITLE
Lab 11 Import file has wrong URL

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#105]
# Module: 10
#### 4  Step: In the Open window, navigate to the D:\DA100\Labs\11-create-power-bi-dashboard\Solution folder.

Description of issue
This file is blocked from being uploaded and the user would need the solution file from lab9 (module 8)
Repro steps:

1.
1.
1.

**Comment by FraSkills3362** [comment]
Maybe folder "D:\DA100\Labs\11-perform-data-analysis-in-power-bi-desktop" is missing a Starter folder.

**Comment by AndrewConniff** [comment]
Well, the instruction is D:\DA100\Labs\11**-create-power-bi-dashboard**\Solution 
Which is module 9, not 11.  When students tried opening the file in  D:\DA100\Labs\11-perform-data-analysis-in-power-bi-desktop - it failed every time... there could be 2 issues here.

- If the intention is to use the folder 11 - the upload fails AND the text in the URL is wrong. 

- If the intention is to use the file from lab 9 - then the text is right and the *number* is wrong

**Comment by shannonlindsay** [comment]
Thanks @FraSkills3362 and @AndrewConniff - you're exactly right. The file from lab 9 was intended and this has been updated. Thanks for your feedback!
