### ISSUE TITLE
Lab instructions for Mod 11 are not following step numbering conventions

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#106]
# Module: 10
#### Step: ??

Description of issue:

Please include the Exercise numbers in the outline like you have done with labs 1-10. 

https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/blob/master/Instructions/Labs/11-perform-data-analysis-in-power-bi-desktop.md 

![Lab 11 outline](https://user-images.githubusercontent.com/53623295/113492452-6c27e280-94a5-11eb-89e7-cfc29bd2a647.PNG)

This helps us refer to a Task easily when discussing Tasks with students. As is, we have multiple Task 1. But being able to reference the Exercise numbers helps with this.

As mentioned, you have done this with labs 1-10 and it will help in this lab too.
Like this:
![Lab 11 outline updated](https://user-images.githubusercontent.com/53623295/113492545-0e47ca80-94a6-11eb-9ec5-7b236105597a.PNG)

Repro steps:

1.
1.
1.

**Comment by shannonlindsay** [comment]
Thanks for helping us remain consistent @FraSkills3362 (and for your always helpful description of issues). This change has been made.
