### ISSUE TITLE
Cleanup slides 

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#107]
# Module: 02

Several Slides have background boilerplate that should have been deleted. Although this should not (normally) show under the animation, it would be proper to use correct template slides and delete unused bolerplate.

![image](https://user-images.githubusercontent.com/17992669/113535922-fe0d1980-9591-11eb-8a1c-726afcabdc49.png)

See slides 7, 8, 9.

**Comment by shannonlindsay** [comment]
Thanks for this feedback @boomalator. This is noted and changes will be reflected in the next course update.
