### ISSUE TITLE
Wrong Terminology - Decomposition Tree

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#109]
# Module: 10
#### Step: 08

Student asked "what's a decision tree?" was this meant to say "decomposition tree"?
"Notice that the decision tree presents resellers, ordered from highest profit margin."

As well, the Headline "Work With Decomposition Tree" restarts the numbering of tasks at one, but is not labelled as an "Exercise" or given a number.  It used to be Lab > Exercise > Task > Step.   If we are doing away with the "Exercise" level, tasks should be numbered without a break.

**Comment by shannonlindsay** [comment]
Thanks @boomalator - this has been updated.
