### ISSUE TITLE
Lab 13 - Missing shortcut

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#11]
> To open Power BI Report Builder, on the taskbar, click the Power BI Report Builder shortcut.

There is no shortcut in the taskbar, at least in the VM image currently deployed to LODS.

Recommend updating either instructions or VM to bring the 2 in sync.

**Comment by shannonlindsay** [comment]
Hi @VitalyMCT - thanks. This is now in Lab 11 - Create Power BI Paginated Report - and the VM image has been updated.
