### ISSUE TITLE
Different labs are mentioning row level security

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#111]
# Module: 00
#### Step: 00

Description of issue: There are still a couple of labs (lab 4 and 7, potentially more as well) which make reference to row-level-security. Since RLS is not anymore part of the labs, this should be removed, or a new lab on RLS should be foreseen

Repro steps:

1. Example Lab 4: In this lab you will create a many-to-many relationship between the **Salesperson** table and the **Sales** table. You will also enforce row-level security to ensure that a salesperson can only analyze sales data for their assigned region(s).
1. Example Lab 7: 	*You may recall that row-level security was configured to ensure users only ever see data for their sales regions and targets. When this report is distributed to salespeople, they’ll only ever see their sales performance results.*
1.

**Comment by shannonlindsay** [comment]
Thanks @weslbo - I will do a thorough look at all of the labs and make this change. Thank you!

**Comment by shannonlindsay** [comment]
Updated to remove RLS. @weslbo - let's discuss this offline.
