### ISSUE TITLE
Typo - "Logo" not "Log"

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#113]
# Module: 08
## Lab/Demo: 09
Exercise: 1
#### Step: 21

Description of issue
Typo - "Logo" not "Log"

![Logo not Log](https://user-images.githubusercontent.com/53623295/115159112-9362e000-a05f-11eb-8562-e8780b088b28.PNG)

Repro steps:

1.It should read: 
To add the company logo, on the menu bar, click Edit, and then select Add a Tile.
Not
To add the company log, on the menu bar, click Edit, and then select Add a Tile.

**Comment by shannonlindsay** [comment]
Thanks @FraSkills3362 - this has been updated. Thanks for the clear instructions :)
