### ISSUE TITLE
Task 3 steps 4-6 UI changes. No longer a prompt to sign in with current credentials. 

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#115]
# Module: 01
#### Step: 04

Description of issue
Task 3
Steps 4-6 have changed in the UI. There is no prompt to sign in with current credentials. 

Repro steps:
https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/blob/master/Instructions/Labs/01-prepare-data-with-power-query-in-power-bi-desktop.md#task-3-get-data-from-sql-server

**Comment by shannonlindsay** [comment]
Thanks for catching this change @hope77777 - lab instructions have been updated to reflect this change.
