### ISSUE TITLE
Lab 1 - Relationship checkboxes

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#119]
Regarding

> While these two options can be helpful when developing a data model, they have been disabled to support the lab experience.

Perhaps we can adjust the wording slightly to make it clear to students that they are the ones who are switching the checkboxes off (earlier in this step)? 

The current wording is being interpreted by some as "the checkboxes are already switched off in the lab environment".

**Comment by shannonlindsay** [comment]
Thanks @VitalyMCT. I have updated it to say: "While having these two options enabled can be helpful when developing a data model, we have just disabled them to support the lab experience." I hope this helps!

**Comment by WigF1** [comment]
Shannon,

That still scans the same. It would be better to say "...data model, you disabled them earlier to support the lab experience."

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by shannonlindsay** [comment]
Thanks for helping me clarify @WigF1 - I've gone ahead and updated the language.
