### ISSUE TITLE
Lab 4 - Minor update to wording and screenshot for boolean properties

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#12]
UI description (and screenshot) in lab instructions:

> In the Properties pane, from inside the Formatting section, slide the Thousands Separator property to On.

Property states are now called Yes/No instead of On/Off.

Actual UI, in PBI Desktop version installed on standard lab VM image:

![image](https://user-images.githubusercontent.com/1765732/94729488-f9d01d00-031e-11eb-9a26-b308b584e965.png)

_Edit: Similar update would apply to other properties in this lab and in other labs._

**Comment by shannonlindsay** [comment]
Thanks @VitalyMCT. Screenshots were updated in the Feb 2021 release.
