### ISSUE TITLE
Missing Step to Filter salesperson Lab 07

### ISSUE THREAD

**Issue by necarlson** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#121]
# Module: 07
#### Step: 05/06

**Description of issue:**
 Target, Variance, and Variance Margin show up with "(Blank)". This is because the Target, Variance, and Variance Margin are related to a salesperson, but there is no filtering done to designate the sales person.

An additional step to select Michael Blyth (to be consistent with screen shots and final solution) would resolve this issue.

**Repro steps:**

1. Complete lab through step 5
2. Notice the fields Target, Variance, and Variance Margin are blank

**Comment by boomalator** [comment]
This is the same issue reported in #120 .

**Comment by shannonlindsay** [comment]
Duplicate issue. See response in #120.
