### ISSUE TITLE
Lab Instruction lists wrong default - Paginated report

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#123]
# Module: 09
#### Step: 3

Description of issue

"In the Select Connection Type dropdown list, notice that Microsoft SQL Server is selected."

Repro steps:

The initial selection is SQL Server Analysis Services. Students must change the selection. Multiple students have reported reading the step and assuming that "Microsoft SQL Server Analysis Services" is the same thing.

**Comment by shannonlindsay** [comment]
@boomalator - thank you! this has been changed to "In the Select Connection Type dropdown list, change the connection type from SQL Server Analysis Services to Microsoft SQL Server." I hope that clears up the confusion!
