### ISSUE TITLE
Instructor Demo Instructions -  Demo 7 - Wrong field for line values

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#128]
# Module: Create Reports
#### Step: 5

To match the screenshot, select Sales | Profit **Margin**, not _Sales | Profit_

Either field will work, except your line will look different than the screen shots.

**Comment by shannonlindsay** [comment]
@boomalator - I am leaving this issue open. I will update the demo instructions for the next release, which is happening sometime in June. Thanks for catching this!

**Comment by boomalator** [comment]
No problem.  I'd presented the course several times wonder why my visual looked different ... :)

**Comment by shannonlindsay** [comment]
Closing this issue - demo will be updated with the August release :)
