### ISSUE TITLE
Module 5 path to snippets file easy to miss.

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#129]
# Module: 05
#### Step: 02

Description of issue
The issue is more of an enhancement - the placement of the path to the snippets file gets missed by multiple attendees , I am not sure how to call it out better except to maybe call it out more than once. 

Repro steps:

1.
1.
1.

**Comment by shannonlindsay** [comment]
Hi Andrew! I think this is an easy fix. Let me see where I can slot it in another time or two. I'll close this issue once it's done.

**Comment by shannonlindsay** [comment]
HI Andrew - I added the message and the file path beneath Task 4 as well, since students are writing DAX there as well. Hopefully this helps!
