### ISSUE TITLE
Lab 13 - Download update prompt

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#13]
The first message displayed after opening Power BI Report Builder is an offer to download an update. This will likely remain the case long-term, unless the lab VM image is continuously and frequently updated.

We should thus add a step to instructions to direct students to either ignore or proceed with the update.

![image](https://user-images.githubusercontent.com/1765732/94737905-d790cc00-032b-11eb-89cd-7d69cde423c6.png)

**Comment by shannonlindsay** [comment]
Hi @VitalyMCT - I am working with the team to get into a more regular cadence with updates to both Power BI desktop and Power BI report builder. I have amended the instructions to have students ignore and am working on the longer term solution. Thanks!
