### ISSUE TITLE
Create DAX Calculations Part 2 instructions are incorrect at Task 2, Step 3. Wrong years are stated in the instructions.

### ISSUE THREAD

**Issue by datarelish** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#130]
# Module: 06 Create DAX Calculations in Power BI Desktop, Part 2
#### Step: 04

Description of issue
The lab materials discuss '2016' and '2017' but 2016 is not in the data. The instructions should read '2017' and '2018' respectively.
Repro steps:

1. Review date data in the database
1. Check the notes and see that the years do not match the dates in the database
1.

**Comment by shannonlindsay** [comment]
Thanks for catching this @datarelish! This change has been made. Thanks for your feedback :)
