### ISSUE TITLE
New lab update

### ISSUE THREAD

**Issue by bhmand** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#131]
Well just to be sure that I am not missing something here. SInce the last update in the labs I can see in the change log that there is no lab for module 1 and 12? And no labs for module 11 and 13 either? 

So if this is correct why do we not have any labs for the last 3 modules. Should the students not learn e.g. to manage workspaces apart from just creating new workspaces? If it is because content is presented in other modules then remove the modules from the Student Handbook.

**Comment by PeterKessler** [comment]
My students did the demo for module 13 and liked it as a lab, so maybe this can be fixed easily.

**Comment by bhmand** [comment]
Yes that would be one way to fix it. And I just read the Trainerprepguide stating the following:

Labs are provided for each module except for modules 12, and 13. 

Which is wrong. No labs for module 1, 11, 12, and 13. :(

**Comment by bhmand** [comment]
And are there any instructions on how to create new accounts/tenants for the students? I guess I have to create a new Office 365 Trial subscription and create the accounts for students myself?

**Comment by shannonlindsay** [comment]
@bhmand - per your original comment, you are correct about the change. You can see a clear mapping of labs to modules on the GitHub [page](https://microsoftlearning.github.io/DA-100-Analyzing-Data-with-Power-BI/). 

It looks like we need to update the Trainer Prep Guide, which I will do with the next release (late June). Thank you for catching that. 

As far as the lab hosting environment goes, this is a great question to post in the courseware forum on [MCT Central](https://www.microsoft.com/en-us/learning/mct-central.aspx). This repo is for feedback on the content, which we greatly appreciate!
