### ISSUE TITLE
Given snippet is wrong

### ISSUE THREAD

**Issue by hoffiemas** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#134]
# Module: DA-100-Allfiles/
#### Step: 00

In snippets.txt the snippet for the month-column is wrong.

Month =
FORMAT('Date'[Date], "yyyy MMM")

correct is (to match the screenshot https://docs.microsoft.com/de-de/learn/modules/create-measures-dax-power-bi/media/lab-6-13-ssm.png#lightbox of the lecture) 

Month =
FORMAT('Date'[Date], "MMM yyyy")

**Comment by WigF1** [comment]
This is for DA-100, not the MS Learn content. The snippet is correct as per the screenshots in the lab.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: hoffiemas ***@***.***>
Sent: Friday, June 4, 2021 7:24:20 PM
To: MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI] Given snippet is wrong (#134)


Module: DA-100-Allfiles/
Lab/Demo: 05
Task: 00
Step: 00

In snippets.txt the snippet for the month-column is wrong.

Month =
FORMAT('Date'[Date], "yyyy MMM")

correct is (to match the screenshot https://docs.microsoft.com/de-de/learn/modules/create-measures-dax-power-bi/media/lab-6-13-ssm.png#lightbox of the lecture)

Month =
FORMAT('Date'[Date], "MMM yyyy")

**Comment by shannonlindsay** [comment]
Thanks @hoffiemas and @WigF1 - glad that you both wrote. We are in the process of syncing the Learn and DA-100 content (happening within the month), so the snippet from DA-100 which @WigF1 has confirmed is correct will be used in both.  We will be updating the VMs and using the same lab content, which should help a) keep everything correct and up to date and b) eliminate confusion. I hope this helps!
