### ISSUE TITLE
Wrong starter file Lab module 13

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#140]
# Module: 13
#### Step: 8

Starter file for lab is created in latest version of Power BI Desktop and it is not possible to open it in version installed in VM.
![PBIDversionissue](https://user-images.githubusercontent.com/4288542/131007162-35913322-bcf7-4401-aeb2-505a7f28b2a4.png)

Solutions
- Update VM to use latest version of Power BI Desktop
- Create starter file in Power BI Desktop installed in VM

**Comment by shannonlindsay** [comment]
@bechynsky - this will be resolved as of this Friday, September 17th.
