### ISSUE TITLE
Suggestion to change instruction M4 Lab 3

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#143]
# Module: 4
#### Step: 2

Description of issue

Step looks little confusing for people. They need to select 12 columns in this step. I recommend to change it to

While pressing the Ctrl key, select the following 12 columns (spanning multiple tables, 13 columns in total including Product | ProductKey column):

**Comment by shannonlindsay** [comment]
Thanks for your suggestion @bechynsky. I will take this in to consideration and will modify accordingly.
