### ISSUE TITLE
Small issue in lab referring to Pie Chart Tool Tip when no Pie chart is in the lab

### ISSUE THREAD

**Issue by jarougha** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#144]
# Module: 07
#### Step: 13

Step 13 refers to "Hover the cursor over different segments of the pie charts to reveal tooltips", but there was no pie charts in the report.

Repro steps:

1. Might mean "Bar charts" instead of "Pie Charts"
1.
1.

**Comment by shannonlindsay** [comment]
Thank you for noticing this @jarougha - this has been corrected to direct users to the bar charts. Thank you!
