### ISSUE TITLE
Lab 3 - UI difference between instructions and Power BI Desktop

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#15]
Refer to this annotated screenshot:

![image](https://user-images.githubusercontent.com/1765732/94831023-70295980-03c9-11eb-8d70-7948ea0a1054.png)

**Comment by VitalyMCT** [comment]
This also applies further down in this same lab.

**Comment by rainpgy1** [comment]
> This also applies further down in this same lab.

can u please tell me how do you import those tables? i can't get those tables

**Comment by Derekp20** [comment]
They are the tables from AdventureworksDW2020 provided in the lab files, or installed in the hosted labs. Lab 2 gets you to import the tables

**Comment by Derekp20** [comment]
Just realised you might have meant the columns in DimProductSubCategory when viewing DimProduct. When selecting the columns in DImProduct, make sure you keep the column that represents the link to DimProductSubCategory. It shows as a grey column in the Query Editor, you might possibly have removed it in a earlier step.

**Comment by shannonlindsay** [comment]
Thanks for starting this thread @VitalyMCT. All screenshots have been updated with the Feb 26 release. @rainpgy1 - please file another issue if you are still having issues with accessing the database. The backup file is located in Allfiles\DA-100-Allfiles\DatabaseBackup.
