### ISSUE TITLE
Update Power BI Desktop to October 2021 build

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#153]
We've seen some glitches around data model updates in labs with the build that's currently on the VMs (August 2021 release). 

These may have to do with the new data model view and related capabilities.

Can you please update the PBI Desktop build on the VMs to the latest build currently available?

**Comment by shannonlindsay** [comment]
@VitalyMCT - a VM update is in process for a December release. The process takes about a month and it has been initiated. The update process will remain quarterly for the foreseeable future. Thanks very much for keeping us posted about what you're seeing and how you've been able to resolve issues - that's very helpful!

**Comment by VitalyMCT** [comment]
@shannonlindsay Would you have a date in mind for the December release please? I am running up to x2 DA-100's next month and would like to understand which session(s) would run on what PBI Desktop version. Thanks again as always.

**Comment by VitalyMCT** [comment]
@shannonlindsay Can we have an update on this one please? I've checked the VM at one of the leading ALHs today and it still has the August PBI Desktop release. Was the December release cancelled?

**Comment by bpmoring** [comment]
Hi @VitalyMCT I just confirmed via LODS that the current version running is the August 2021 version. I will be following up with the labs team to make sure we get the update loaded. Thanks again for confirming this for us.

**Comment by VitalyMCT** [comment]
Thanks @bpmoring . 

To confirm my understanding, were the baseline VMs upgraded and it's just a matter of propagating them to LODS? Or is the baseline still at PBI Desktop August 2021? If the baseline was upgraded, what version of PBI Desktop is on it now?

FYI, I happen to be teaching DA-100 on LODS starting this Monday.

**Comment by bpmoring** [comment]
It appears that the baseline is still at the August 2021 version. So, for your session on Monday it will continue to be that version. I will make sure to update you here when I confirm.

**Comment by VitalyMCT** [comment]
@bpmoring & @shannonlindsay  Would it be possible to get an update on this one? 

IMO this really needs to be resolved on a priority basis, to be consistent with Microsoft Power BI Product Group's guidance. From https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-get-the-desktop:

![image](https://user-images.githubusercontent.com/1765732/151667608-5e44c4a1-2825-476e-bce3-8f23f9759152.png)
