### ISSUE TITLE
Map and filled map visuals are now off by default in the admin portal

### ISSUE THREAD

**Issue by shannonlindsay** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#154]
### Task: 1

Description of issue: Map and filled map visuals are now off by default in the admin portal.  In order for learners to create the map for lab 7, the map visual must be enabled in the Power BI admin portal.

![image](https://user-images.githubusercontent.com/77289548/141189663-c2306d92-3879-41e7-bfbc-5010a6a1e3f3.png)

**Comment by TesterTesterson1004** [comment]
Thanks for posting this, we ran into this exact issue today and enabling those options did appear to allow reports using maps visualizations to be displayed successfully in the poiwerbi.com portal when using the assigned Tenant.

 Do you know if this settings tweak to the 2 entries is planned to be incorporated into the instructions for this module?

**Comment by shannonlindsay** [comment]
Hi @TesterTesterson1004 - yes! Turning map and filled map visuals on in the admin portal is being added to the beginning of Lab 7, which will be updated tomorrow, 11/19. Thanks for helping us keep this course up to date!

**Comment by bpmoring** [comment]
This update has been made.
