### ISSUE TITLE
Wrong screenshot Lab 08, Exercise 04, Task 02, Step 03

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#159]
# Module: 07
#### Step: 03

Wrong screenshot. Students were very confused. See attachment.
![DA100L08E04T02S03](https://user-images.githubusercontent.com/4288542/145223775-c4227334-bac9-4826-8527-15641a7da485.png)

**Comment by bpmoring** [comment]
Thank you. I will take a look at this and update.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue and has submitted PR #167

**Comment by bpmoring** [comment]
This issue has been resolved.
