### ISSUE TITLE
Bothell misspelled in Module 10 Lab 1 instructions

### ISSUE THREAD

**Issue by shinnickr13** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#160]
# Module: 10
#### Step: 06

Description of issue
Bothell is spelled correctly in the key influencers visualization but is spelled Bothel in the instructions.

Repro steps:

1. Follow module 10 lab 1 steps until exercise 5, task 1, step 6
2. With "increase" selected in key influencers visualizations you can see Bothell is spelled with 2 Ls but the instructions have it spelled with 1 L
![image](https://user-images.githubusercontent.com/95879812/145456575-f3e37eec-66d5-4ee5-8eed-e4a46cacd36c.png)
![image](https://user-images.githubusercontent.com/95879812/145456590-b3d9fa21-93b0-42a8-bcae-5e17ae6903f4.png)

**Comment by bpmoring** [comment]
Thank you for bringing this to my attention. I will make the update.

**Comment by shannonlindsay** [comment]
Closed in conjunction with MOC review.
