### ISSUE TITLE
Minor typo in Module 4 Lab: Model Data in Power BI Desktop, Part 2

### ISSUE THREAD

**Issue by richbrooks** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#162]
# Module: Module 4 - Design a Data Model in Power BI
#### Step: 20

Minor Typo:   "reactive"  should be "reactivate".

Credit to student Josh Cain in my DA-100 course 12/15/21

**Comment by bpmoring** [comment]
Thanks for pointing this out. We will address this with an update on Friday.

**Comment by shannonlindsay** [comment]
Closed in conjunction with MOC review.
