### ISSUE TITLE
"Perform Data Analysis in Power BI Desktop" Lab

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#170]
Can we please add "Advanced" to the name of the lab to match the module name and contents? Or otherwise highlight the fact that this is going into advanced analysis territory (as the previous labs have all been doing analysis).

**Comment by bpmoring** [comment]
Thank you @VitalyMCT I will look into updating the lab title.
