### ISSUE TITLE
Module 8 : 09-create-power-bi-dashboard

### ISSUE THREAD

**Issue by manishrps** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#171]
# Module: 08
#### Step: 01

Description of issue
While running the file (UpdateDatabase-2-Addsales.ps1) getting error, it's show an error about specified path is not correct .

<img width="852" alt="github" src="https://user-images.githubusercontent.com/55728764/150090649-89933e2f-ab3a-4337-86a8-31d6e16cb183.png">

Please revert back as soon as possible!
Thank you!

@seesharprun @VitalyMCT @GraemeMalcolm @Eric2XU

**Comment by bpmoring** [comment]
Thank you @manishrps I will look into this and correct.

**Comment by VitalyMCT** [comment]
I am unsure as to the reason I've been tagged on this :)

The reason for the error is that the user is running the PS script twice. The script is trying to insert a record that already exists, thus erroring out.

A safeguard can be added to the script to allow it to be re-runnable. Or a note can be added to instructions telling the students how to deal with this common issue.

**Comment by bpmoring** [comment]
Thanks for the info @VitalyMCT I will pass this on to the lab team for correction.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.
