### ISSUE TITLE
Module: 5 Lab/Demo: 2 some data already saved as completed in Lab

### ISSUE THREAD

**Issue by philip-young** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#174]
# Module: 5
### Task: Exercise 2 Task 1: Create a YTD measure, Task 2: Create a YoY growth measure, Task 3: Finish up

Description of issue
The Lab file already has some steps fully completed. In both Task 1: Create a YTD measure, Task 2: Create a YoY growth measure
the Measures already exist that you are asked to create so you get an error.

Also in Task 1 it mentions going to Page 2, however the Page doesn't actually exist in the file that is loaded. There is a visual that is referenced that needs to be there to build on with future steps; I had to figure out how to make one of my own.

Lastly, in Task 3: Finish up you are asked to 'Delete Page 3 also', however that Page doesn't exist nor was it created.

**Comment by bpmoring** [comment]
Thank you @philip-young, we will look into this.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
