### ISSUE TITLE
Wrong screenshot

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#176]
# Module: 04
##### Step: 09

Screenshot should point to OrderDate field
![L03E03T01S09](https://user-images.githubusercontent.com/4288542/160618038-21eb4344-f9a6-4b8a-a755-f117a9250b18.jpg)
.

**Comment by bpmoring** [comment]
This has been updated in the PL-300 Lab. Thanks!
