### ISSUE TITLE
Pl300 Lab 5 pointing to the wrong starter file

### ISSUE THREAD

**Issue by elenamoor** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#177]
# Module: 5
#### Step: 6

Description of issue
This lab points to the starter which already has all of the measures and created relationship that learners are supposed to create. I assume that this file is more advanced than needed and belongs to the next lab.

Repro steps:
Pull the mentioned starter and try to execute Task 2 step 1+2. The error will be shown that the table already exists. Ping me for any additional questions: Elena Moor, MTT
![PL300-lab5bug](https://user-images.githubusercontent.com/15022465/161658551-984ca00c-827b-423f-a2e0-cf574757e9f4.JPG)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
