### ISSUE TITLE
Module 8 Lab 8 Path is incorrect for SQL script - pointing to old course folder

### ISSUE THREAD

**Issue by jarougha** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#178]
# Module: 08 Create a Power BI Dashboard - Exercise 2, Task 1
#### Step: 00

Description of issue
Path in Setup/Scripts/UpdateDatabase-2.sql is pointing to a path for DA100 instead of a path for PL300
Repro steps:

1.Change Script location to PL300 or
2.Change Script location to be a relative path based on the course name

Screen Shot for GitHub sql file
![Lab8SQLScriptPath](https://user-images.githubusercontent.com/70500407/162091118-be576f23-a411-43fc-9962-6dbd3c83290e.png)

**Comment by bpmoring** [comment]
This has been updated on the PL300 lab repo. Thanks!
