### ISSUE TITLE
Lab Timing

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#19]
Discussion item...

My feeling is that the common 45 minute time allocation for the labs, although sufficient for some, is substantially underestimated for others. For example, Lab 03A seems to require closer to 1 hour or even 1.5 hours.

What do the other MCTs think? 

Perhaps we can post actual timings here and thus help refine the suggested timings.

**Comment by VitalyMCT** [comment]
Adding a bit of data to support the need for different timing.

Lab 3A vs. Lab 10A, currently at same 45 minute suggested duration. Lab 3A has more than 2x the instructions.

Yes, lines of instructions does not directly translate into lab duration. However, it's a decent proxy.

![image](https://user-images.githubusercontent.com/1765732/94839961-f4cda500-03d4-11eb-852d-55c3a1a95c2a.png)

![image](https://user-images.githubusercontent.com/1765732/94840005-044cee00-03d5-11eb-82a8-e9bb250cf644.png)

**Comment by shannonlindsay** [comment]
@VitalyMCT - the labs have been slightly reworked and should all take around the same amount of time. If further discussion around timing is required, let's move to the MCT Courseware forum. Thanks!
