### ISSUE TITLE
The only demo is a Lorem Ipsum placeholder

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#2]
https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/blob/master/Instructions/Demos/DEMO_deploying_an_arm_template.md

**Comment by ilikesql** [comment]
hi Vitaly - 
We'll have this removed from the Github repo, this is a remainder from a publication issue
