### ISSUE TITLE
Lab 08A - Toolbox UI

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#22]
The version of Power BI Desktop installed on the standard lab VM is June 2020. The UI shown in the instructions for this lab is from an older release. 

Small thing sure, however, can cause a bit of confusion with students. Recommend updating the screenshot(s). Example:

![image](https://user-images.githubusercontent.com/1765732/94844015-d10d5d80-03da-11eb-9312-82493e0634a9.png)

**Comment by shannonlindsay** [comment]
Hi @VitalyMCT - thanks for the detailed feedback. Updated screenshots are included in the Feb 2021 release.
