### ISSUE TITLE
Lab 08A - Screenshot update for accessing Full Screen mode

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#23]
Power BI Service UI has changed a little bit. Labels for menu gone, replaced by icons.

In instructions:

![image](https://user-images.githubusercontent.com/1765732/94845066-60ffd700-03dc-11eb-849d-7493f6b210a6.png)

In current Power BI service:

![image](https://user-images.githubusercontent.com/1765732/94845112-7412a700-03dc-11eb-8ee4-945c8285e985.png)

**Comment by shannonlindsay** [comment]
Thanks for this heads up @VitalyMCT. All screenshots have been updated with the Feb 2021 release.
