### ISSUE TITLE
Lab 10A - Q&A Boxes

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#26]
Minor discrepancy between color of boxes in instructions and color in Power BI UI. 

Perhaps the color reference can be removed altogether?

![image](https://user-images.githubusercontent.com/1765732/95131955-d38df100-0713-11eb-9f41-09ba087af620.png)

**Comment by shannonlindsay** [comment]
Thanks @VitalyMCT . This has been taken care of with the updated labs in the Feb 2021 release.
