### ISSUE TITLE
Lab 10A - Discrepancies in Q&A behaviour

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#27]
There are a couple of places that require updates to instructions:

The following 2 steps are not needed. They were already completed in the report built in the previous lab, 9A (i.e. report used in this dashboard)

![image](https://user-images.githubusercontent.com/1765732/95132757-2025fc00-0715-11eb-9c1e-fdad2a6294b3.png)

Getting a different result in the step that says 

> Notice the response of (Blank).

Here's the difference:

![image](https://user-images.githubusercontent.com/1765732/95133091-9a568080-0715-11eb-957b-0be8b9b8e567.png)

Similarly, getting a different result in the step that says 

> Notice the response is now $33M.

![image](https://user-images.githubusercontent.com/1765732/95133254-e275a300-0715-11eb-8aa5-9a155f25427d.png)

**Comment by shannonlindsay** [comment]
Thanks @VitalyMCT. With the updated labs in the Feb 2021 release, all labs are designed to be used as stand-alone modules. This step still appears with a note. It is intentional.
