### ISSUE TITLE
Lab 10A - Markdown glitch

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#29]
Screenshot:

![image](https://user-images.githubusercontent.com/1765732/95134296-7c8a1b00-0717-11eb-951b-aa0a1e10fd07.png)

**Comment by shannonlindsay** [comment]
Thanks @VitalyMCT. This has been taken care of with the updated labs in the Feb 2021 release.
