### ISSUE TITLE
I created a cross reference for the Labs that may help until MS addresses this

### ISSUE THREAD

**Issue by speedglide** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#3]
DA-100T00 Lab Cross Reference

Module 4, Lab 1, page 126, Data Modeling in PowerBI Desktop https://bit.ly/3hKfeWa
Module 4, Lab 2, page 141 Advanced Data Modeling in Power BI https://bit.ly/2DcZOef
Module 5, Lab 1, page156 Introduction to DAX in Power BI https://bit.ly/308IIa5
Module 5, Lab2, page 156 Advanced DAX in Power BI Desktop https://bit.ly/3hKfeWa
Module 7, Lab 1, page 255 Designing a Report in Power BI https://bit.ly/3fdEMcu
Module 7, Lab 2, page 293 Enhancing Power BI Reports with Interaction and Formatting https://bit.ly/30e9deF
Module 8, Lab, page 328 Creating a Power BI Dashboard https://bit.ly/309FUJZ
Module 9, Lab, page 350 Creating a Paginated Report https://bit.ly/307PH36
Module 11, Lab, page 442 Publishing and Sharing Power BI Content  ***Can’t find***

**Comment by ilikesql** [comment]
Thanks for doing this mapping, one of the things we are considering for an upcoming update is to "rename the lab folders" to more compelling names rather than Lab numbers.
