### ISSUE TITLE
Lab 12A - Broken image markdown

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#33]
![image](https://user-images.githubusercontent.com/1765732/95384798-f8b06a00-08a1-11eb-9587-49040410ad16.png)

**Comment by shannonlindsay** [comment]
This lab is no longer part of the course. Publishing and sharing Power BI content has been moved to an instructor demo per the Feb 21 course update.
