### ISSUE TITLE
Lab 2a - Markdown problem generating path

### ISSUE THREAD

**Issue by sqlgeekster** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#34]
# Module: 02
#### Step: 1

Description of issue
Markdown is generating a bad file path display.  See Screenshots below.  
![Screen Shot 2020-10-09 at 11 29 49 AM](https://user-images.githubusercontent.com/11856973/95619365-60da8980-0a23-11eb-9cb5-01cd517f9e62.png)
![Screen Shot 2020-10-09 at 11 32 41 AM](https://user-images.githubusercontent.com/11856973/95619394-6df77880-0a23-11eb-87f7-9130a5c0de91.png)

Repro steps:

1.
1.
1.

**Comment by shannonlindsay** [comment]
Thanks @sqlgeekster - this has been updated.
