### ISSUE TITLE
Lab 1A - Power BI Service shortcut

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#38]
> Tip: You can also use the Power BI Service favorite on the Edge favorites bar.

The VM image currently deployed to ALHs does not have this favorite link. 

Recommend removing the sentence or adjusting the VM image to match.

**Comment by shannonlindsay** [comment]
Thanks @VitalyMCT - this has been sorted with the Feb 21 course updates - the old Lab 1 no longer exists.
