### ISSUE TITLE
Labfile storage

### ISSUE THREAD

**Issue by Derekp20** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#4]
At the end of each lab files are saved on the D: drive. If you are using the hosted labs, these are lost because of the restart for each module. It could be worth suggesting the use of OneDrive to store files that are worked on. Particularly if delegates have created an Office 365 subscription for the course. My preference is to create a trial subscription for the class and create an account for each delegate, using OneDrive would work well here.

**Comment by ilikesql** [comment]
Appreciate the suggestion, will take this back to our content team for future consideration.
