### ISSUE TITLE
Lack of instructions for Demos

### ISSUE THREAD

**Issue by damjan071** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#40]
Trainer Preparation Guide says: "The course has numerous demonstrations. Take the time to work through each one and decide which to use."

Where can I find instructions for the Demos I should show during the course?

**Comment by Derekp20** [comment]
There are none, you need to look at the labs and work out a few demonstrations based on the tasks involved in the labs - no need to demonstrate the whole lab!

**Comment by shannonlindsay** [comment]
@damjan071 and @Derekp20 - demo instructions, files, and videos have now been added (per Feb 21 update) to the course content and can be accessed here (instructions and files) and in the MCT download center (videos). We hope these are helpful!
