### ISSUE TITLE
Add a .dacpac to restore database to a Azure SQL Database 

### ISSUE THREAD

**Issue by Theelepel** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#42]
# Module: 01

Description of issue
Would be nice to have a .dacpac in addition to the .bak file. So users would be able to restore it to a Azure SQL Database (Azure SQL DB does not support .bak)

**Comment by molenaar** [comment]
While waiting for an update, you can first remove the readonlyuser from the security table (it is orphaned).
![image](https://user-images.githubusercontent.com/10166617/99179965-8180b800-2722-11eb-8597-ed88d410de95.png)

 and after that export the AdventureWorksDW2020 to a bacpac file.
![image](https://user-images.githubusercontent.com/10166617/99179970-88a7c600-2722-11eb-9a8a-d048cfd54d23.png)

You can export the bacpac file directly to a storage account which makes importing the database much easier in Azure.

I have also created multiple backups:
1. Backup AdventureWorksDW2020.bacpac after running the UpdateData-1-UpdateAccount.ps1 in Lab 01A
2. Backup AdventureWorksDW2020-Mod10.bacpac after running the UpdateData-2-AddSales.ps1 and UpdateData-3-AddPartnerAccount.ps1 in Lab 10A

In PowerBI Desktop you can update your database connection strings (via Options and Settings->Data source settings) to switch between one of the database.

Good luck!

**Comment by shannonlindsay** [comment]
@Theelepel - the database backup for AdventureWorks is now here on GitHub, along with the database backup for the instructor demos (located in Allfiles/DA-100-Allfiles/DatabaseBackup/).
