### ISSUE TITLE
Course Notes Reports

### ISSUE THREAD

**Issue by jbeidleman** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#44]
Description of issue
Since MCTs are left to write their own demos, it would be helpful if the reports which were used for the screen shots in the course notes (Power Point slides) were provided so we could build our demos using those reports. This would help MCTs to maintain some consistency between the slides, demos and labs which would help the students too.

**Comment by WigF1** [comment]
The current content of the 'course' has been taken directly from the MS Learn free content. This is why there are no demos included at the moment. It wasn't designed with MOC delivery in mind (my opinion).

You may be able to look on MS Learn for some downloadable files.

**Comment by shannonlindsay** [comment]
@jbeidleman - demo instructions, files, and videos have now been added (per Feb 21 update) to the course content and can be accessed here (instructions and files) and in the MCT download center (videos). We hope this helps!
