### ISSUE TITLE
Lab 6a, Ex1, Task 3, 13. Syntax error

### ISSUE THREAD

**Issue by Theelepel** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#46]
#### Step: 13

Description of issue
Syntax error
Repro steps:
Paste the code:
MonthKey =

(YEAR('Date'[Date]) * 100) + MONTH('Date'[Date]) + MONTH ( [Date] ))

It should be without the last ')':

MonthKey =

(YEAR('Date'[Date]) * 100) + MONTH('Date'[Date]) + MONTH ( [Date] )

**Comment by FraSkills3362** [comment]
Actually, shouldn't it be:
---------------
MonthKey =

(YEAR('Date'[Date]) * 100) + MONTH('Date'[Date])
----------------
Without the last +MONTH( [Date] ) Like the Snippets.txt file says in the files in the Lab06A\Assets\ folder?

**Comment by shannonlindsay** [comment]
Thanks @Theelepel and @FraSkills3362 - this is now Lab 5 - Create DAX Calculations in Power BI Desktop, Part 1. The correct syntax for the month key is: 

MonthKey = 
(YEAR('Date'[Date]) * 100) + MONTH('Date'[Date])

This is now indicated in the Lab instructions and the Solution File.
