### ISSUE TITLE
Labs are missing

### ISSUE THREAD

**Issue by bhmand** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#47]
Labs are missing for module 10+11+13 according to the description.

**Comment by Derekp20** [comment]
Lab numbering does not line up with the modules, this is my reckoning, but it would be really good if they could be renumbered to match the modules!

Mod 1 - Lab 1a
Mod 2 - Lab 2a
Mod 3 - Lab 3a
Mod 4 - Lab 4a & 5a
Mod 5 - Lab 6a & 6b
Mod 6 - None
Mod 7 - Lab 8a & 9a
Mod 8 - Lab 10a
Mod 9 - Lab 13a
Mod 10 - Lab 11a
Mod 11 - Lab 12a
Mod 12 - None
Mod 13 - None

**Comment by bhmand** [comment]
Well I guess the lab for module 13 is still missing? And yes I agree.. It is a complete mess.. And does the Labs 
Online work correct then? When testing it seems like Lab13a is the last one!

**Comment by shannonlindsay** [comment]
@bhmand and @Derekp20 - thanks for your contributions. The labs have been reordered and the name of the lab now matches the name of the module. We hope this helps!
