### ISSUE TITLE
6a ex 1 task 1 step 2

### ISSUE THREAD

**Issue by AustinP00** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#48]
# Module: 6a
#### Step: 2

Description of issue:
- creating new table  --> unable to rename table. Instructions show a phrase appended on the original table name but BI desktop will not allow the renaming because of reuse of the initial tables name.

**Comment by shannonlindsay** [comment]
@AustinP00 - this is now Lab 5 - Create DAX Calculations in Power BI Desktop, Part 1. You are correct that the tables must have 2 different names. The starter file now has the original table named according to the instructions, as Salesperson (Performance). Students will now be able to easily create Salesperson. Thanks for the feedback!
