### ISSUE TITLE
imported csv files need gateway

### ISSUE THREAD

**Issue by erikvani** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#49]
# Module: 8
#### Step: 1

Description of issue
dataset created in previous lab needs gateway.

Repro steps:

1.
![image](https://user-images.githubusercontent.com/22495273/101473718-777d5e00-394a-11eb-8650-8fe018f5b860.png)

1.
1.

**Comment by shannonlindsay** [comment]
@erikvani - all labs were updated in Feb 2021 and each lab has been designed to function stand alone. I am closing this issue. Thank you for contributing!
