### ISSUE TITLE
Lab 3A - Reference to DimProductSubCategory

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#51]
Exercise 1, Task 3, Step 11:

>Notice that the transformation resulted in two columns, and that the DimProductCategory column has been removed.

The expanded and hence removed column is DimProductSubCategory rather than DimProductCategory

**Comment by shannonlindsay** [comment]
Thanks @VitalyMCT - this has been addressed in the Feb 2021 version (now Lab 2 - Load Data in Power BI Desktop).
