### ISSUE TITLE
Lab 3A - StandardCost expansion

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#52]
Exercise 1, Task 6, Step 4:

> Expand the DimProduct column, and then include the StandardCost column.

I suggest adding "only" qualifier before "include", or otherwise making it clear that other columns should be excluded. By default all columns from the expanded table are selected.

**Comment by shannonlindsay** [comment]
Thanks @VitalyMCT. This has been addressed in the Feb 2021 updates.
