### ISSUE TITLE
Lab06A Ex1 Task4 Step 4  Simple Spelling issue

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#53]
# Module: 06
#### Step: 4

Description of issue
     Simple Spelling issue
Repro steps:

1.The step currently says: Create the follow two model relationships:
2.Change "follow" to "following"
3.The step should read: Create the following two model relationships:

**Comment by shannonlindsay** [comment]
Thanks @FraSkills3362 - this update has been made.
