### ISSUE TITLE
Lab 08A Ex1 Task3 step 25 Change "Visuals" to "Columns" in the explaination

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#55]
Lab 08A Ex1 Task3 step 25

Description of issue:
The explanation accidentally used the wrong term.  It says:
By dragging visuals into a visual, they will be added to default wells. 

It should say:
By dragging **columns** into a visual, they will be added to default wells. 

Repro steps:

1. Please change the word visuals to columns.

**Comment by luconsta** [comment]
I think a better change would be "By dragging **fields** into a visual"

Also at:
Exercise 2: Explore the Report / Step 10 Hover the cursor over different segments of the **pie** charts to reveal tooltips

There are no pie charts into report so I think it would be more appropriate to change to:

Hover the cursor over different segments of the **bar** charts to reveal tooltips.

**Comment by shannonlindsay** [comment]
Thanks @FraSkills3362 and @luconsta - this has been updated.

**Comment by shannonlindsay** [comment]
Thanks @FraSkills3362 and @luconsta - this has been updated.
