### ISSUE TITLE
Lab 08A Ex2 Task1 Step 9 Change button name to Focus Mode

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#56]
# Module: 8
#### Step: 9

Description of issue: Name of button needs to be updated in the instructons

Repro steps:

1.  Change:
Hover the cursor over the map visual, and then at the top-right, click the **In Focus** icon.
To:
Hover the cursor over the map visual, and then at the top-right, click the **Focus Mode** icon.

**Comment by shannonlindsay** [comment]
Thanks @FraSkills3362 - this has been updated.
