### ISSUE TITLE
Lab 09A Ex1 Task1 Setp 4 Unnecessary step - not in context - please delete

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#57]
#### Step: 4

Description of issue: Unnecessary step - not in context - please delete. 

Change 
Should step 4 be removed? Step 1 had us go to Power BI Desktop, but step 4 seems to be a command from Power BI Services and not Power BI Desktop, therefore, not needed here and not able to be preformed.

Repro steps:

1. Remove Step 4

**Comment by shannonlindsay** [comment]
This has been updated with the Feb 21 course updates. Thanks @FraSkills3362.
