### ISSUE TITLE
Lab 09A Ex3 Task1 step 2 Incorrect verbiage.

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#58]
Mod 09A
Exercise 3
Task 1
Step 2
Change :
In the visual fields pane, for the Profit Margin…
TO
In the Visualizations Pane, in the Fields list, for the Profit Margin…

**Comment by shannonlindsay** [comment]
Thanks @FraSkills3362 - this has been updated.
