### ISSUE TITLE
Lab 01A Ex1 Task2 Step8

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#59]
Lab 01A Ex1 Task2 Step8

Description of issue

This step is no longer needed. This button has been removed by Microsoft.

Repro steps:
Remove Step 8
"In the Power BI service, at the top-right corner, if the “New Look” is not enabled, click the slider control to turn it on."

**Comment by shannonlindsay** [comment]
Thanks for this catch @FraSkills3362 - this has been taken care of with the Feb 21 updates.
