### ISSUE TITLE
Could anyonw know where to download the lab file and the lab setup manual?

### ISSUE THREAD

**Issue by megabyte711** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#6]
# Module: 00
#### Step: 00

Either at the learning download center or GitHub, the lab files and the lab setup manual are not there.
Also issued a support ticket at the trainingsupport.microsoft.com for days but still pending for the solution.

Could anyone here know where to download the lab files and the manual?

Repro steps:

1. Missing any pbix file
1. Miss all the excel data source files.
1.

**Comment by Derekp20** [comment]
If you access one of the hosted labs e.g. LearnOnDemand, the files are in the VM. The question is where did they get them from. Each lab tells you to click on a button to download the latest files, so there must be a source somewhere!

Here is a copy I made for the time being https://github.com/Derekp20/DA-100

**Comment by megabyte711** [comment]
Thank you so much, Derekp20

**Comment by VitalyMCT** [comment]
The files were posted here subsequently to this ticket being opened. 

Location: https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/tree/master/Allfiles/DA-100-Allfiles
