### ISSUE TITLE
Lab 01A Ex1 Task3 Step2-5

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#60]
Lab 01A Ex1 Task3 Step2-5

Description of issue: I believe we can delete these steps now as the site has changed. I have tested 3 times.
2. When prompted to upgrade your account to Power BI Pro, click Try Free.

Picture 17

A Power BI Pro license is required to create and work with workspaces. It’s also required when sharing content. The trial will allow you to work with Pro features for up to 60 days.

3. When prompted to start the 60-day free Pro trial, click Start Trial.

Picture 18

4.When the trial has been extended, click Close.

5. Repeat the first step in this task to create the workspace.

Repro steps:
Consider removing the steps above

**Comment by shannonlindsay** [comment]
Thanks @FraSkills3362 - lab 1 has been removed as of Feb 2021. Thanks for the feedback.
