### ISSUE TITLE
Lab 11A Ex: 5 Task:1 Step: 5 Incorrect work used in step

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#61]
Lab 11A
Ex: 5
Task:1
Step: 5

Description of issue: Incorrect work used in step.
Step 5 says: At the top-left of the visual, notice that Key Influencers is in focus, and the specific influence is set to understand what **includes** profit margin to increase.

I believe it should say: At the top-left of the visual, notice that Key Influencers is in focus, and the specific influence is set to understand what **influences** profit margin to increase.

Repro steps:
Change the word "includes" to "influences"

**Comment by AustinP00** [comment]
committed replacement to make direct change to instructions.

**Comment by shannonlindsay** [comment]
Thanks @AustinP00 and @FraSkills3362. This is now lab 10 - Perform Data Analysis in Power BI Desktop and I have made the update. Thank you for the assist!
