### ISSUE TITLE
Old Power BI Desktop on VM images

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#62]
According to Power BI Product Group's guidance from https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update:

> ...Important. Power BI Desktop is updated and released on a monthly basis, incorporating customer feedback and new features. **Only the most recent version of Power BI Desktop is supported...**

To be consistent with this recommendation the lab VMs should be upgraded from June 2020 release to a current release. And of course have the instructions be brought in sync as well.

**Comment by shannonlindsay** [comment]
Hi Vitaly - this is noted and will be fixed in the 2/12 update.
