### ISSUE TITLE
Lab 09A / Exercise 5 / Task 1 / Step 2 - clarification for drill-through

### ISSUE THREAD

**Issue by luconsta** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#63]
# Module: 07
#### Step: 02

Description of issue

The step instructions:

> To test the drill through report, in the **Quantity by Category** visual, right-click the **Clothing** bar, and then select **Drill Through | Product Details**.

would be better to read:

> To test the drill through report, on the **Overview** page, in the **Quantity by Category** visual, right-click the **Clothing** bar, and then select **Drill Through | Product Details**.

It is important to make sure you are in the right page, because it might not be the page the report opens with. 
Even the named visual (**Quantity by Category**) exist only there.

**Comment by shannonlindsay** [comment]
Thanks @luconsta - this has been updated!
