### ISSUE TITLE
ALL new lab files have steps numbering problem

### ISSUE THREAD

**Issue by luconsta** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#64]
Description of issue

All new lab files starting with:
**[01-prepare-data-with-power-query-in-power-bi-desktop.md](https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/blob/master/Instructions/Labs/01-prepare-data-with-power-query-in-power-bi-desktop.md)**
and ending with
**[11-create-power-bi-paginated-report.md](https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/blob/master/Instructions/Labs/11-create-power-bi-paginated-report.md)**

have steps numbering problems because of the **Lab Story** part that have 11 points, then every **Extercise 1 / Task 1** will start from **12**.  Then the next exercise will continue step numbering not resetting back to 1.
Older labs  named d**a-100-_NN_a_instructions.md** will reset the steps to 1 at each exercise and task.

Or this is intended from now on?

**Comment by shannonlindsay** [comment]
Hi @luconsta - thank you. We inadvertently pushed new labs up before we were ready. Note that the next release is scheduled for 2/12 and I will look into the numbering issue in the mean time.
