### ISSUE TITLE
readme.md "Download Latest Student Handbook and AllFiles Content" pointing to "garbage" 

### ISSUE THREAD

**Issue by luconsta** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#68]
Hello,

In [readme.md](https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/blob/master/readme.md) at very beginning of the file there is a link: [Download Latest Student Handbook and AllFiles Content](https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/releases/latest) that is pointing to an useless area where are some garbage ZIP files that contains one demo and one lab with "Lorem ipsum" data.

Please delete the link or modify it to point to proper data.

Kind Regards,
Lucian

**Comment by shannonlindsay** [comment]
Thanks Lucian. I have updated the ReadMe to reflect the changes to the repo. All necessary files can now be found in Allfiles/DA-100-Allfiles/.
