### ISSUE TITLE
Dowloading DA-100-Allfiles.exe blocked by Microsoft SmartScreen

### ISSUE THREAD

**Issue by luconsta** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#69]
Hello,

Can you talk with your colleagues from SmartScreen to "allow" this file to download without so many clicks?... ;-)

Initially is blocked at download by Edge
![DA-100-Allfiles_Blocked_Explorer](https://user-images.githubusercontent.com/32492990/107122665-b758b700-68a1-11eb-99e9-347c11314d8f.png)

and after manage to "keep" the file, when running the EXE the SmartScreen strikes again and you have to click dozen of times again. :)

![DA-100-Allfiles_Blocked_SmartScreen](https://user-images.githubusercontent.com/32492990/107122710-03a3f700-68a2-11eb-9154-c63d21578b09.png)

Kind Regards,
Lucian

**Comment by shannonlindsay** [comment]
Hi Lucian - can you please confirm that you are able to access the files now? I will try to look into why it's being flagged - thank you for letting us know. As long as you can successfully use the files I will be closing this issue.

**Comment by luconsta** [comment]
Hi Shannon,
Thank you for your message, but the issue no longer exist, because there is no "DA-100-Allfiles.exe" file to download now. ;-)
Kind Regards,
Lucian
