### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#7]
Can we get GitHub Pages enabled for this repo, like for other recent MOCs such as for example AZ-204?

https://microsoftlearning.github.io/AZ-204-DevelopingSolutionsforMicrosoftAzure

**Comment by WigF1** [comment]
Seconded. This would be a great addition. Although, it seems the push for this course seems to be the free content on /Learn

**Comment by shannonlindsay** [comment]
@VitalyMCT and @WigF1 - this is something we can likely implement. Let me do a little bit of research and I will get back to you both here. Thanks for your feedback.

**Comment by shannonlindsay** [comment]
Thanks again for this suggestion. This has been implemented and can be found at https://microsoftlearning.github.io/DA-100-Analyzing-Data-with-Power-BI/.

**Comment by VitalyMCT** [comment]
Thanks @shannonlindsay , much appreciated!
