### ISSUE TITLE
Backup of TailspinToys2020-US database?

### ISSUE THREAD

**Issue by dancostello70** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#74]
# Module: 2-13
## Demo: 2-13

The demos all refer to the "TailspinToys2020-US" database, but I'm unable to find a backup or .bacpac of that database anywhere. Could it be added to the repo? Thank you!

**Comment by shannonlindsay** [comment]
Hi Dan - thanks for letting us know! I've added the TailspinToys2020-US database backup in Allfiles\DA-100-Allfiles\DatabaseBackup.

**Comment by dancostello70** [comment]
Thank you so much, Shannon!
