### ISSUE TITLE
Why not use useful filenames for PowerPoint?

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#76]
# Module: ALL

Why not use meaningful names?

Example: DA-100 Mod0-ENU-PowerPoint.pptx

Most instructors only have one language of the files. Even if I were to have English and French, I would have them in different folders.  In any case, I *know* it's PowerPoint. Even if I wasn't sure, the "pptx" is a give-away. It is not needed to state that this is a power point file.

What would be useful:
- two-digit module numbers (for sorting)
- the module topic

So, instead of DA-100 Mod0-ENU-PowerPoint.pptx
use DA-100 Mod00 Introduction.pptx

I mean, yes, most of us rename them all anyway, and cut out the useless adverts for our competition. But it would be nice if some logic were applied at the source.

**Comment by shannonlindsay** [comment]
Thanks for the feedback @boomalator - there are a number of behind the scenes reasons for the naming convention, but I will surface this request to the publishing team.

**Comment by boomalator** [comment]
If there are behind the scenes reasons for deliberately inconveniencing the customers who deliver the content (and pay for it), then the behind-the-scenes processes are broken and should be significantly revamped. I would be intrigued to know what "process" requires that the word "powerpoint" be included in the name of a .pptx file so that you know its.... well, a pptx file; and what process -prevents- including a description of the content, or a two-digit number.

**Comment by shannonlindsay** [comment]
Hi @boomalator - thanks for the continued feedback. We're going to update the file names slightly, to maintain publishing guidelines and also make things easier for trainers. We're not opposed to making things make sense! You will see these updates in the March 26th release.
