### ISSUE TITLE
Significance of Stock Photos

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#77]
# Module: ALL

What is the purpose or significance of including approximately 35 photo's of the same gentleman's posterior.

There is nothing in the stock photography that implies anything to do with Power BI. No one is using any form of device to view any form of data. In fact, they appear to be using a spiral paper pad.

Although it appears to have two races represented, it is not particularly representative of either age or gender.

So, what value does this photo add for the student?

**Comment by shannonlindsay** [comment]
Thanks for this feedback @boomalator - we will consider this for the next update.
