### ISSUE TITLE
Wrong word on slide (may also be in book)

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#78]
# Module: 11
## Slide 17 of 21

Unless Data Protection is renting rooms in an apartment building, I think you mean "tenet".

**Comment by shannonlindsay** [comment]
Thanks for this @boomalator - we must have had M365 tenants on the mind ;)  I have updated the wording in the slide deck which will be published on Friday the 26th. Thank you!
