### ISSUE TITLE
Non-Existent Lab: Publishing and Sharing Power BI Content

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#79]
# Module: 11
## Lab/Demo: 11? 10? Lab 9 3/4 (If it existed, it would it be numbered right?)

Description of issue

DA-100 Mod11-ENU-PowerPoint.pptx, Slide 18
![image](https://user-images.githubusercontent.com/17992669/111708177-fe27be00-880a-11eb-9a0b-bccad56ebc6c.png)

No such lab that I can find
![image](https://user-images.githubusercontent.com/17992669/111708275-2d3e2f80-880b-11eb-90a7-675e9159d2e4.png)

**Comment by shannonlindsay** [comment]
Thanks @boomalator - you are correct, there is no lab for this module. The slides have been updated accordingly and will be released in the learning download center (and replaced here) on Friday, March 26th. Publishing and Sharing Power BI content has been moved to an instructor demo.
