### ISSUE TITLE
Module 3 - Slides Do Not Match Student Content

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#80]
# Module: 03

Description of issue

Students expect that their reference "book" and the slides relate to each other. Whether that's right, wrong, beneficial or stupid, that's what they expect and that's how it's been for all the 25+ years that I've been an MCT.  If Learning is now deciding that books and slides and labs are all independent sources of different content, then you need to communicate that much more clearly to the audiences: Students, Learning Centers and Instructors, because IMO none of us expect it to have changed.

# Problems Include:
## Different Wording in titles:
- "Profiling the Data" != "Data Profiling"
- "Enhance" vs "Enhancing"
- "Shaping the Data" != "Data Shaping"
- "Pivot and Unpivot" vs "Unpivot and Pivot Columns" [Which should be columns AND ROWS, can't have one without the other in a Pivot]
- "Review Questions" vs "Knowledge Check"
- "Profiling Data" vs "Profiling Data and Examining Structures"
## A Lesson with one slide/page of content (Profiling).

I seriously thought I had the wrong slides downloaded. How does this not get documented and fixed? Does everyone else just accept and expect that that it will be this way?

# Repro steps:

## Student Book (Skillpipe):
![image](https://user-images.githubusercontent.com/17992669/111708788-19df9400-880c-11eb-8758-6641bb3a9811.png)

## PowerPoint:
![image](https://user-images.githubusercontent.com/17992669/111708843-2fed5480-880c-11eb-81d8-6e4f87aca159.png)

![image](https://user-images.githubusercontent.com/17992669/111708896-501d1380-880c-11eb-9ad5-5b1d414c4f1f.png)

**Comment by WigF1** [comment]
I think it's arguable we can refer to this course as MOC - the student 'manual' is nothing more than a copy / paste from the Microsoft Learn Power BI content.

https://docs.microsoft.com/en-us/learn/powerplatform/power-bi

The text / images etc are taken right from it. In my opinion, the differences in modules and numbers are as a result of trying to 'MOCify' it.

The same thing was true for the old (first) Power BI course too. 10989A was taken from a free EDx course called DAT207; this course was made for free back when PBI Desktop had two tabs on the ribbon. This in turn was still used for 10989B and then used as the basis for 20778A.

With regards your Module 3 screenshots, to see what I mean, look at the text and images in SkillIPipe and compare them to https://docs.microsoft.com/en-us/learn/modules/clean-data-power-bi/

Like I say, given the MS Learn content appeared before the 'MOC', I imagine they have merely repurposed.

**Comment by shannonlindsay** [comment]
Thanks for this feedback @boomalator and @WigF1. We are working to maintain/update the content and do appreciate concrete suggestions (like consistent naming in titles and consistent ordering). This course is having a minor update published on the 26th of March, which will address some of the issues listed above.  Please feel free to add additional actionable suggestions here.

**Comment by shannonlindsay** [comment]
I am pleased to report that the issues described here have been updated. If there is anything that was mistakenly missed please log a new issue.
