### ISSUE TITLE
Poor Quality (Low Value) Review Questions

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#81]
# Module: 10

What is the purpose of review questions? To review things discussed? To reinforce knowledge? To prepare for certification?
Many of the Review Questions do not do these things and do not add value to the material.

For example:
Q03 - I have determined through extensive testing that the Q&A feature also does not allow me to book a grooming appointment for my dog.  There are 45,746,234,121 possible correct answers for this question and only one wrong answer for this question. 

Q04 - The decomposition tree does not enable me to automatically diagram the syntax of German grammar, either. These questions are of exceedingly low value, and would, I hope, be quickly culled from any certification preparation material.

![image](https://user-images.githubusercontent.com/17992669/111728617-d9474100-8832-11eb-913d-34448d20bb6b.png)

**Comment by shannonlindsay** [comment]
Thanks for your suggestion @boomalator - we will take this under review as the course evolves. We appreciate your contributions and commitment to helping us improve the course.
