### ISSUE TITLE
Simple verbiage change "left" to "right"

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#82]
# Module: 2
## Lab 1: ? Prepare Date in Power BI Desktop
Exercise 1: Prepre Data
#### Step: 2 To close the getting started window, at the top-left of the window, click X.

Description of issue
The X is in the top-right corner not the top-left corner. Please change "left" to "right"

Repro steps:

1.
1.
1.

**Comment by shannonlindsay** [comment]
Thanks @FraSkills3362 - this has also been updated. Thanks for contributing!
