### ISSUE TITLE
Verbiage change "Right" to "Left"

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#83]
# Module: 2
## Lab: 1? Prepare Date in Power BI Desktop
Exercise 1: Prepre Data
#### Step 7  Click Save.
Tip: You can also save the file by click the Save icon located at the top-right.

Description of issue
Is it just me? :) The save button is in the top-left corner NOT the top-right corner.

Change "right" to "left"

Repro steps: 

1.
1.
1.

**Comment by shannonlindsay** [comment]
Thanks @FraSkills3362 - this has been updated!
