### ISSUE TITLE
Spelling: "Sales" not "sale"

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#86]
# Module: 05
## Lab 5 Create DAX Calculations in Power BI Desktop, Part 1
Exercise 1: Create Calculated Tables
#### Step: 11. In the Properties pane, in the Description box, enter: Salesperson related to sale

Description of issue
enter: Salesperson related to sale
should read
enter: Salesperson related to Sales

Repro steps:

1.Change the word "sale" to "Sales"
1.
1.

**Comment by shannonlindsay** [comment]
Thanks @FraSkills3362 - this has been updated
