### ISSUE TITLE
Text box for entering text for the student does not seem to work with Shift-Enter as a character

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#87]
# Module: 05
## Lab: 5 Create DAX Calculations in Power BI Desktop, Part 1
Exercise 1: Create Calculated Tables
#### Step: 3 In the formula bar, enter the following:

![step 3](https://user-images.githubusercontent.com/53623295/111888774-f0fb0280-89b5-11eb-9d11-3b2254e5a810.PNG)

Description of issue
When the student clicks the T box to have the formula typed for them, it only types the first row (nothing after the Shift-Enter that is after "Date =")
Repro steps:

1. I would leave out the Shift-Enter and make the statement one line, but you may have other solutions.
1.
1.

**Comment by shannonlindsay** [comment]
Hi @FraSkills3362 - are you saying that using shift + enter in the formula bar does not create a line break in the lab environment?

**Comment by FraSkills3362** [comment]
The shift+enter works fine.

We have text boxes that the student can click on (box the a “T” inside) and it will type the code for them…so they don’t have to type code.
The text boxes that are provided in the instructions are never get past the Shift-Enter.

So, the text box should type for the student:
Date =
CALENDARAUTO(6)

However, it only types:
Date =

Maybe this is another lab provider thing.

**Comment by jbeidleman** [comment]
I could be wrong, but I think that is a Learn On Demand issue. Microsoft provides the expressions in a text file to copy and paste. I have reported the problem to LOD on a previous revision but they still haven't fixed it. I instruct my students to use the text files to paste in the code instead of using that feature. It does work well for the email account and password though from Resources.

**Comment by shannonlindsay** [comment]
@FraSkills3362  and @jbeidleman - thanks for this confirmation. I am working with the Lab on Demand team now and will update you here in this thread. Thanks for bringing this to our attention! And also for providing the workaround.

**Comment by FraSkills3362** [comment]
I now see this as a known error for Learning on Demand-along with their workaround. 
![TextBoxKnowError](https://user-images.githubusercontent.com/53623295/112180799-414eac00-8bd2-11eb-8645-597f2050f77a.PNG)

You can close this. Thanks.
