### ISSUE TITLE
Small error in lab 1 regarding the path to store the solution

### ISSUE THREAD

**Issue by Theelepel** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#89]
# Module: 1
#### Step: 16

Description of issue
In lab 1 it refers to D:\DA100\Solution folder while the path should be 

D:\DA100\**My**Solution folder.

The Github also uses the correct path.

**Comment by boomalator** [comment]
This was an LOD error. They said they fixed it last week. If it still persists, open a ticket with them. You can tell them to cross-reference my ticket Lab Errors in Instructions DA100 (Ticket 281850).

**Comment by FraSkills3362** [comment]
I also use LOD. It looks good to me now.

**Comment by shannonlindsay** [comment]
Closing this error as it has been fixed.
