### ISSUE TITLE
Lab 1 - Power BI Pro trial creation process

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#9]
The trial activation process is a little different now from the time the instructions were written. Differences include:

> When prompted to upgrade your account to Power BI Pro, click Try Free.

This screenshot now includes 3 selections instead of 2.

> When prompted to start the 60-day free Pro trial, click Start Trial.

This step is no longer present. At least it's not present in my Microsoft 365 tenant. Here's the screenshot that appears instead:

![image](https://user-images.githubusercontent.com/1765732/94720961-60027300-0312-11eb-8a8b-ee664ff397f2.png)

> When the trial has been extended, click Close.

These instructions activate the trial rather than extend it. Also, there is no longer a Close button in the workflow.

**Comment by VitalyMCT** [comment]
Further to the below. The O365 account on the tenant Microsoft provides to ALHs already has the Pro tier activated. 

So this entire task is no longer necessary and should be removed. 

Alternatively, we should ask students to check if they are on Pro and if so, skip the task.

**Comment by shannonlindsay** [comment]
@VitalyMCT - Lab 1 no longer includes this content as of the Feb update. Please reach out to me if you are still having issues with licensing as it relates to lab instructions.
