### ISSUE TITLE
Minor verbiage change to Lab 6

### ISSUE THREAD

**Issue by FraSkills3362** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#90]
## Lab: 6 Create DAX Calculations in Power BI Desktop, Part 2
Exercise 2: Create Measures
#### Step: 3 Click the down-arrow for Unit Price, and then notice the available menu options.

Description of issue

The current note in the instructions reads:
Visible numeric columns allow report authors at report design to decide **time** how column values will summarize (or not). 

I think they meant something like:
Visible numeric columns allow report authors at report design **time** to decide how column values will summarize (or not). 

Repro steps:

1.
1.
1.

**Comment by shannonlindsay** [comment]
Thanks for catching this @FraSkills3362 - this has been updated.
