### ISSUE TITLE
What is DAX Content?

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#92]
# Module: 05
## Slide 11

What is "DAX Content"
Did you mean "Context"? 
Other than this title, the term "DAX Content" does not appear in the instructor guide or student book that I can find.

Speaking of context, the two slides that follow have no context on the slide. They are totally dependent on verbal explanation from the instructor (which is fine, I suppose, as it makes me useful).

**Comment by shannonlindsay** [comment]
@boomalator - thanks - this is indeed a typo. It's been corrected in the slides and SkillPipe - changes will be reflected as of 26 March.
