### ISSUE TITLE
Lab on RLS should perhaps be on at least the same DAY as the content on RLS?

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#93]
# Module: Lab in Module 3, Content in Module 13, Lab is numbered 4.
### Task: All

Content and explanation of Row Level Security is introduced in Module 13.
Why is this exercise in this lab?

(See issue #75 about my concerns that Lab 4 is presented in Module 3, as a bad numbering scheme, as well.)

**Comment by shannonlindsay** [comment]
Hi @boomalator - this has been changed and RLS is no longer a part of Lab 4 - Model Data in Power BI Desktop, Part 2. You will see this reflected here on the 26th of March. Your point about the numbering scheme has been taken under consideration - we're working through the best way to address it.
