### ISSUE TITLE
Incorrect connotation of cardinality

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#94]
# Module: 06
#### Slide 13 / Review Question

This modules discusses the (common) description of cardinality meaning uniqueness. The module does not discuss "direction that data flows".  (Leaving aside for the moment that the data is not moving at all and doesn't really "flow" anyway).

Most common definitions of "Cardinality" in data modelling do not reference "Data Flow". When referring to "uniqueness" they usually include the word "data" as in "data cardinality".

https://en.wikipedia.org/wiki/Cardinality_(data_modeling), https://orangematter.solarwinds.com/2020/01/05/what-is-cardinality-in-a-database/

However, if the course is going to describe both meanings: the (someone odd "flow" name for relationship, and the data cardinality or uniqueness), the review question and answer should match the concept being discussed in the module.

**Comment by shannonlindsay** [comment]
Thanks for catching this @boomalator - this has been addressed and will be reflected as of the 26 March updates. The question/answer has been revised.
