### ISSUE TITLE
MFA/Security Defaults

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#96]
While this may be dependent on the Lab Provider, Azure Security Defaults, MFA, and Conditional Access should be OFF for all users, even the default admin user in the created tenant. Notwithstanding that, the lab instructions should (somewhere) tell the student what to do if they get the "must provide more info" prompt and/or how to disable this.

**Comment by shannonlindsay** [comment]
Thanks @boomalator. I need to do a little research - I'll look into adding this into the instructions.

**Comment by boomalator** [comment]
According to LODS support, something somewhat randomly triggers Azure to start requesting 2FA registration even when the 2FA/SD/CA policies are all disabled. It's "opaque" as to the security "reason" for this. You might what you chat with LODS as well. Their ticket is 286215.

**Comment by shannonlindsay** [comment]
Thanks for the additional info @boomalator - this is really helpful! I'll update this thread once I know more.

**Comment by luconsta** [comment]
Hello,

To get rid of the "annoying" warning "**Help us protect your account. Microsoft has enabled Security Defaults to keep your account secure**", just press on the link [Learn more](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-security-defaults) on that screen and should take you to the page that explaining why this is the "_default option for any tenant created after October 22, 2019_" and with instructions on how could be disabled.

HTH.

**Comment by boomalator** [comment]
1. Security Defaults are (and should be) disabled I. This tenant.

2. This is not an Azure admin course and many data analysts have never used Azure. (Microsoft keeps perpetuating the myth that Power BI is an azure product and that students show up to th is course experienced in Azure.)

3. That’s not the message I was getting.

4. If we are going to run the labs alone default mode with SD or CA or 2FA turned on, that’s “fine-I-suppose” but then the lab instruction need to match what the student sees.

5. Students are (rightfully) extremely reluctant to tie their personal credit cards or phones to a training lab. This has been a consistently un-solved problem since the first time azure or office 365 was ever used in a course.



If you wish to spend the time in your classroom to deal with it, that’s certainly fine. But I think the course should be seamless.


Mobile: big fingers, little buttons, and don't get me started about autocorrect.

On Mar 26, 2021, at 3:39 PM, luconsta ***@***.***> wrote:

﻿Hello,

To get rid of the "annoying" warning "Help us protect your account. Microsoft has enabled Security Defaults to keep your account secure", just press on the link Learn more<https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-security-defaults> on that screen and should take you to the page that explaining why this is the "default option for any tenant created after October 22, 2019" and with instructions on how could be disabled.

HTH.

**Comment by shannonlindsay** [comment]
@boomalator - note that we've taken this feedback into consideration for the next lab update. I will update this thread when I have a date - it will likely be in May.

**Comment by boomalator** [comment]
Thank you, Shannon. 

I ran this course for ESI this past week and did NOT encounter this issue.

**Comment by shannonlindsay** [comment]
Good to know @boomalator , thank you! I'll look into it (to understand why/how it got fixed) - but closing the issue. Thanks for the feedback!
