### ISSUE TITLE
Naming issue with File to be saved

### ISSUE THREAD

**Issue by JoshuaRoweTTS** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#97]
# Module 2
#### Step 16
 
o	This step required me to save a backup file to the same file the original was in. This couldn’t be done due to the naming collision.
o	Suggest changing the name of the backup to add the suffix (1).

**Comment by shannonlindsay** [comment]
@JoshuaRoweTTS - is this referring to the save as step? In lab 2?

**Comment by shannonlindsay** [comment]
@JoshuaRoweTTS - closing this issue. Please log another issue with more detail and feel free to ask questions if you are still encountering this issue.
