### ISSUE TITLE
Error value in all cells of the newly created ‘cost’ column

### ISSUE THREAD

**Issue by JoshuaRoweTTS** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#98]
# Module 2
#### Step 8
 
o	The step resulted in an error value in all cells of the newly created ‘cost’ column. See below.

![image](https://user-images.githubusercontent.com/80295628/112451890-b8866a80-8da1-11eb-8f1f-d2c8cbbec0c3.png)

**Comment by shannonlindsay** [comment]
Hi @JoshuaRoweTTS - I am not able to reproduce this error. I am going to leave the issue open for others to comment until the end of the month. Without seeing your source file I can recommend that you cross-check the syntax, cross-check your data types in the source columns [TotalProductCost], [Order Quantity], and [StandardCost]. If there are steps we're missing (where data type was set or something else I may be missing), please let me know!
