### ISSUE TITLE
Sign in button has changed

### ISSUE THREAD

**Issue by JoshuaRoweTTS** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#99]
# Module: 07
#### Step 3

o	Sign in button for MS ‘PowerBI.com’ has been updated. See below:

![image](https://user-images.githubusercontent.com/80295628/112453063-0485df00-8da3-11eb-824d-9a42613a89b9.png)

**Comment by shannonlindsay** [comment]
Thanks @JoshuaRoweTTS - I've confirmed and replaced the image.
